### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sorrycc** [umijs/tnf#2]
## v0.1.0

- [x] route、build、create
- [x] dev
- [x] user config
- [x] preview
- [x] generate

## v0.2.0

- [x] the framework unified plugin system
- [ ] ssr (build, none stream, stream, meta, ppr, ...)
- [ ] tanstack query
- [x] tailwindcss
- [ ] bundle with webpack
- [x] config cmd (set, get, list) @xiaohuoni #43
- [ ] route file simplify (e.g. export component only) 
- [ ] generate with ai

## v0.3.0

- [ ] ssg
- [ ] route with config (hold)
- [x] html
- [ ] bundle deps
- [ ] parser using rust

## v0.4.0

- [ ] server function
- [ ] other ai features

## v0.5.0

- [x] doctor
- [ ] constraint
- [x] performance: chunk preload by routes
- [ ] bundle with vite
- [ ] tnf package
- [ ] [interactive config](https://github.com/BuilderIO/micro-agent?tab=readme-ov-file#config-ui)
- [ ] interactive dev

## others

- [x] example: hackernews
- [x] example: [tnf-ant-design-pro](https://github.com/umijs/tnf-ant-design-pro) Independent maintenance https://github.com/umijs/tnf-ant-design-pro/issues/1  
- [x] example: shadcn/ui + tailwindcss
- [ ] example: todo app
- [x] clickToComponent
- [x] phantom dependency check
- [x] mock
- [ ] gui
- [x] try https://react-scan.million.dev/
- [ ] try https://million.dev/
- [ ] plugin should be compatible with vite
- [ ] error code
- [ ] [unused check with knip or depcheck](https://edvins.io/cleaning-up-dead-files-in-your-react-project)

## docs

- [ ] how to organize route component

**Comment by Xy2002** [comment]
@sorrycc 对Tailwind CSS有什么特别的需求吗~ 我想试着做一些贡献

**Comment by sorrycc** [comment]
@Xy2002 还没具体想过，期望的方式是通过配置一键开启但不内置依赖，比如 tailwindcss: {} 。需要调研下竞品，看下怎么集成会用着比较顺。

**Comment by Xy2002** [comment]
> @Xy2002 还没具体想过，期望的方式是通过配置一键开启但不内置依赖，比如 tailwindcss: {} 。需要调研下竞品，看下怎么集成会用着比较顺。

在`Tailwind`的官网里写到 *Tailwind CSS 作为 PostCSS 插件安装是将其与构建工具（如 webpack、Rollup、Vite 和 Parcel）集成的最无缝方式*。看了一下几个框架，例如：在 `Nuxt` 中启用对 `Tailwind` 的支持是通过 [@nuxtjs/tailwindcss](https://github.com/nuxt-modules/tailwindcss) 这个插件，它本质上是在注册`PostCSS`插件以支持 `Tailwind`，又或者 `Next.js` 和 `SvelteKit` 都是通过 `PostCSS` 插件以支持 `Tailwind`。 但是`tnf`使用`mako`作为构建工具，而`mako`好像目前还无法使用`PostCSS`，所以应该不能使用 `PostCSS Plugins` 的方式对`Tailwind CSS`进行支持。

因此，我的想法是按照类似于`umi/plugins/tailwindcss`的方式，使用 Tailwind  CLI 来实现对Tailwind CSS的支持。

**Comment by sorrycc** [comment]
@Xy2002 嗯，可以先这么做。
